// Civ 4 BTS — hardcoded starter data set
// All values sourced from BTS game mechanics

export const UNITS = [
  {
    id: "scout",
    name: "Scout",
    image: "assets/units/Scout.png",
    strength: 1,
    cost: 15,
    moves: 2,
    firstStrikes: 0,
    firstStrikeChances: 0,
    withdrawalChance: 0,
    collateralDamage: 0,
    collateralDamageLimit: 0,
    collateralDamageMaxUnits: 0,
    combatLimit: 100,
    unitCombatType: "recon",
    immuneToFirstStrikes: false,
  },
  {
    id: "warrior",
    name: "Warrior",
    image: "assets/units/Warrior.png",
    strength: 2,
    cost: 15,
    moves: 1,
    firstStrikes: 0,
    firstStrikeChances: 0,
    withdrawalChance: 0,
    collateralDamage: 0,
    collateralDamageLimit: 0,
    collateralDamageMaxUnits: 0,
    combatLimit: 100,
    unitCombatType: "melee",
    immuneToFirstStrikes: false,
    cityDefenseBonus: 25,
  },
  {
    id: "incan_quechua",
    replaces: "warrior",
    name: "Quechua",
    image: "assets/units/Quechua.png",
    strength: 2,
    cost: 15,
    moves: 1,
    firstStrikes: 0,
    firstStrikeChances: 0,
    withdrawalChance: 0,
    collateralDamage: 0,
    collateralDamageLimit: 0,
    collateralDamageMaxUnits: 0,
    combatLimit: 100,
    unitCombatType: "melee",
    immuneToFirstStrikes: false,
    cityDefenseBonus: 25,
    bonusVsArcher: 100,
    freePromotions: ['combat1'],
  },
  {
    id: "galley",
    name: "Galley",
    image: "assets/units/Galley.png",
    strength: 2,
    cost: 50,
    moves: 2,
    firstStrikes: 0,
    firstStrikeChances: 0,
    withdrawalChance: 0,
    collateralDamage: 0,
    collateralDamageLimit: 0,
    collateralDamageMaxUnits: 0,
    combatLimit: 100,
    unitCombatType: "naval",
    immuneToFirstStrikes: false,
  },
  {
    id: "trireme",
    name: "Trireme",
    image: "assets/units/Trireme.png",
    strength: 2,
    cost: 50,
    moves: 2,
    firstStrikes: 0,
    firstStrikeChances: 0,
    withdrawalChance: 0,
    collateralDamage: 0,
    collateralDamageLimit: 0,
    collateralDamageMaxUnits: 0,
    combatLimit: 100,
    unitCombatType: "naval",
    immuneToFirstStrikes: false,
    attackBonusVsGalleys: 50,
    defenseBonusVsGalleys: 50,
  },
  {
    id: "archer",
    name: "Archer",
    image: "assets/units/Archer.png",
    strength: 3,
    cost: 25,
    moves: 1,
    firstStrikes: 1,
    firstStrikeChances: 0,
    withdrawalChance: 0,
    collateralDamage: 0,
    collateralDamageLimit: 0,
    collateralDamageMaxUnits: 0,
    combatLimit: 100,
    unitCombatType: "archery",
    immuneToFirstStrikes: false,
    cityDefenseBonus: 50,
    hillsDefenseBonus: 25,
  },
  {
    id: "babylon_bowman",
    replaces: "archer",
    name: "Babylonian Bowman",
    image: "assets/units/Bowman.png",
    strength: 3,
    cost: 25,
    moves: 1,
    firstStrikes: 1,
    firstStrikeChances: 0,
    withdrawalChance: 0,
    collateralDamage: 0,
    collateralDamageLimit: 0,
    collateralDamageMaxUnits: 0,
    combatLimit: 100,
    unitCombatType: "archery",
    immuneToFirstStrikes: false,
    cityDefenseBonus: 50,
    hillsDefenseBonus: 25,
    bonusVsMelee: 50,
  },
  {
    id: "caravel",
    name: "Caravel",
    image: "assets/units/Caravel.png",
    strength: 3,
    cost: 60,
    moves: 3,
    firstStrikes: 0,
    firstStrikeChances: 0,
    withdrawalChance: 0,
    collateralDamage: 0,
    collateralDamageLimit: 0,
    collateralDamageMaxUnits: 0,
    combatLimit: 100,
    unitCombatType: "naval",
    immuneToFirstStrikes: false,
  },
  {
    id: "portugal_carrack",
    replaces: "caravel",
    name: "Carrack",
    image: "assets/units/Carrack.png",
    strength: 3,
    cost: 60,
    moves: 3,
    firstStrikes: 0,
    firstStrikeChances: 0,
    withdrawalChance: 0,
    collateralDamage: 0,
    collateralDamageLimit: 0,
    collateralDamageMaxUnits: 0,
    combatLimit: 100,
    unitCombatType: "naval",
    immuneToFirstStrikes: false,
  },
  {
    id: "mali_skirmisher",
    replaces: "archer",
    name: "Mali Skirmisher",
    image: "assets/units/Skirmisher.png",
    strength: 4,
    cost: 25,
    moves: 1,
    firstStrikes: 1,
    firstStrikeChances: 1,
    withdrawalChance: 0,
    collateralDamage: 0,
    collateralDamageLimit: 0,
    collateralDamageMaxUnits: 0,
    combatLimit: 100,
    unitCombatType: "archery",
    immuneToFirstStrikes: false,
    cityDefenseBonus: 50,
    hillsDefenseBonus: 25,
  },
  {
    id: "chariot",
    name: "Chariot",
    image: "assets/units/Chariot.png",
    strength: 4,
    cost: 30,
    moves: 2,
    firstStrikes: 0,
    firstStrikeChances: 0,
    withdrawalChance: 10,
    collateralDamage: 0,
    collateralDamageLimit: 0,
    collateralDamageMaxUnits: 0,
    combatLimit: 100,
    unitCombatType: "mounted",
    immuneToFirstStrikes: false,
    noDefensiveBonus: true,
    attackBonusVsAxemen: 100,
  },
  {
    id: "persia_immortal",
    replaces: "chariot",
    name: "Immortal",
    image: "assets/units/Immortal.png",
    strength: 4,
    cost: 30,
    moves: 2,
    firstStrikes: 0,
    firstStrikeChances: 0,
    withdrawalChance: 10,
    collateralDamage: 0,
    collateralDamageLimit: 0,
    collateralDamageMaxUnits: 0,
    combatLimit: 100,
    unitCombatType: "mounted",
    immuneToFirstStrikes: false,
    bonusVsArcher: 50,
    attackBonusVsAxemen: 100,
  },
  {
    id: "spearman",
    name: "Spearman",
    image: "assets/units/Spearman.png",
    strength: 4,
    cost: 35,
    moves: 1,
    firstStrikes: 0,
    firstStrikeChances: 0,
    withdrawalChance: 0,
    collateralDamage: 0,
    collateralDamageLimit: 0,
    collateralDamageMaxUnits: 0,
    combatLimit: 100,
    unitCombatType: "melee",
    immuneToFirstStrikes: false,
    bonusVsMounted: 100,
  },
  {
    id: "native_america_dog_soldier",
    replaces: "axeman",
    name: "Dog Soldier",
    image: "assets/units/Dog Soldier.png",
    strength: 4,
    cost: 35,
    moves: 1,
    firstStrikes: 0,
    firstStrikeChances: 0,
    withdrawalChance: 0,
    collateralDamage: 0,
    collateralDamageLimit: 0,
    collateralDamageMaxUnits: 0,
    combatLimit: 100,
    unitCombatType: "melee",
    immuneToFirstStrikes: false,
    bonusVsMelee: 100,
  },
  {
    id: "zulu_impi",
    replaces: "spearman",
    name: "Impi",
    image: "assets/units/Impi.png",
    strength: 4,
    cost: 35,
    moves: 2,
    firstStrikes: 0,
    firstStrikeChances: 0,
    withdrawalChance: 0,
    collateralDamage: 0,
    collateralDamageLimit: 0,
    collateralDamageMaxUnits: 0,
    combatLimit: 100,
    unitCombatType: "melee",
    immuneToFirstStrikes: false,
    bonusVsMounted: 100,
    freePromotions: ['combat1'],
  },
  {
    id: "maya_holkan",
    replaces: "spearman",
    name: "Holkan",
    image: "assets/units/Holkan.png",
    strength: 4,
    cost: 35,
    moves: 1,
    firstStrikes: 0,
    firstStrikeChances: 0,
    withdrawalChance: 0,
    collateralDamage: 0,
    collateralDamageLimit: 0,
    collateralDamageMaxUnits: 0,
    combatLimit: 100,
    unitCombatType: "melee",
    immuneToFirstStrikes: true,
    bonusVsMounted: 100,
  },
  {
    id: "explorer",
    name: "Explorer",
    image: "assets/units/Explorer.png",
    strength: 4,
    cost: 40,
    moves: 2,
    firstStrikes: 0,
    firstStrikeChances: 0,
    withdrawalChance: 0,
    collateralDamage: 0,
    collateralDamageLimit: 0,
    collateralDamageMaxUnits: 0,
    combatLimit: 100,
    unitCombatType: "recon",
    immuneToFirstStrikes: false,
    freePromotions: ['guerilla1', 'woodsman1'],
  },
  {
    id: "galleon",
    name: "Galleon",
    image: "assets/units/Galleon.png",
    strength: 4,
    cost: 80,
    moves: 4,
    firstStrikes: 0,
    firstStrikeChances: 0,
    withdrawalChance: 0,
    collateralDamage: 0,
    collateralDamageLimit: 0,
    collateralDamageMaxUnits: 0,
    combatLimit: 100,
    unitCombatType: "naval",
    immuneToFirstStrikes: false,
  },
  {
    id: "trebuchet",
    name: "Trebuchet",
    image: "assets/units/Trebuchet.png",
    strength: 4,
    cost: 80,
    moves: 1,
    firstStrikes: 0,
    firstStrikeChances: 0,
    withdrawalChance: 0,
    collateralDamage: 100,
    collateralDamageLimit: 50,
    collateralDamageMaxUnits: 6,
    combatLimit: 75,
    unitCombatType: "siege",
    immuneToFirstStrikes: false,
    noDefensiveBonus: true,
    cityAttackBonus: 100,
    collateralImmuneVs: ["siege"],
  },
  {
    id: "egypt_warchariot",
    replaces: "chariot",
    name: "War Chariot",
    image: "assets/units/War Chariot.png",
    strength: 5,
    cost: 30,
    moves: 2,
    firstStrikes: 0,
    firstStrikeChances: 0,
    withdrawalChance: 10,
    collateralDamage: 0,
    collateralDamageLimit: 0,
    collateralDamageMaxUnits: 0,
    combatLimit: 100,
    unitCombatType: "mounted",
    immuneToFirstStrikes: true,
    noDefensiveBonus: true,
    attackBonusVsAxemen: 100,
  },
  {
    id: "aztec_jaguar",
    replaces: "swordsman",
    name: "Jaguar Warrior",
    image: "assets/units/Jaguar.png",
    strength: 5,
    cost: 35,
    moves: 1,
    firstStrikes: 0,
    firstStrikeChances: 0,
    withdrawalChance: 0,
    collateralDamage: 0,
    collateralDamageLimit: 0,
    collateralDamageMaxUnits: 0,
    combatLimit: 100,
    unitCombatType: "melee",
    immuneToFirstStrikes: false,
    cityAttackBonus: 10,
    freePromotions: ['woodsman1', 'combat1'],
  },
  {
    id: "axeman",
    name: "Axeman",
    image: "assets/units/Axeman.png",
    strength: 5,
    cost: 35,
    moves: 1,
    firstStrikes: 0,
    firstStrikeChances: 0,
    withdrawalChance: 0,
    collateralDamage: 0,
    collateralDamageLimit: 0,
    collateralDamageMaxUnits: 0,
    combatLimit: 100,
    unitCombatType: "melee",
    immuneToFirstStrikes: false,
    bonusVsMelee: 50,
  },
  {
    id: "greek_phalanx",
    replaces: "axeman",
    name: "Phalanx",
    image: "assets/units/Phalanx.png",
    strength: 5,
    cost: 35,
    moves: 1,
    firstStrikes: 0,
    firstStrikeChances: 0,
    withdrawalChance: 0,
    collateralDamage: 0,
    collateralDamageLimit: 0,
    collateralDamageMaxUnits: 0,
    combatLimit: 100,
    unitCombatType: "melee",
    immuneToFirstStrikes: false,
    bonusVsMelee: 50,
    defenseBonusVsChariots: 100,
  },
  {
    id: "catapult",
    name: "Catapult",
    image: "assets/units/Catapult.png",
    strength: 5,
    cost: 50,
    moves: 1,
    firstStrikes: 0,
    firstStrikeChances: 0,
    withdrawalChance: 0,
    collateralDamage: 100,
    collateralDamageLimit: 50,
    collateralDamageMaxUnits: 6,
    combatLimit: 75,
    unitCombatType: "siege",
    immuneToFirstStrikes: false,
    noDefensiveBonus: true,
    collateralImmuneVs: ["siege"],
  },
  {
    id: "carthage_numidian_cavalry",
    replaces: "horse_archer",
    name: "Numidian Cavalry",
    image: "assets/units/Numidian Cavalry.png",
    strength: 5,
    cost: 50,
    moves: 2,
    firstStrikes: 0,
    firstStrikeChances: 0,
    withdrawalChance: 20,
    collateralDamage: 0,
    collateralDamageLimit: 0,
    collateralDamageMaxUnits: 0,
    combatLimit: 100,
    unitCombatType: "mounted",
    immuneToFirstStrikes: true,
    noDefensiveBonus: true,
    bonusVsMelee: 50,
    attackBonusVsCatapults: 50,
    flankingStrikes: { catapult: 100, trebuchet: 100 },
    freePromotions: ['flanking1'],
  },
  {
    id: "korean_hwacha",
    replaces: "catapult",
    name: "Hwacha",
    image: "assets/units/Hwacha.png",
    strength: 5,
    cost: 50,
    moves: 1,
    firstStrikes: 0,
    firstStrikeChances: 0,
    withdrawalChance: 0,
    collateralDamage: 100,
    collateralDamageLimit: 50,
    collateralDamageMaxUnits: 6,
    combatLimit: 75,
    unitCombatType: "siege",
    immuneToFirstStrikes: false,
    noDefensiveBonus: true,
    bonusVsMelee: 50,
    collateralImmuneVs: ["siege"],
  },
  {
    id: "sumerian_vulture",
    replaces: "axeman",
    name: "Vulture",
    image: "assets/units/Vulture.png",
    strength: 6,
    cost: 35,
    moves: 1,
    firstStrikes: 0,
    firstStrikeChances: 0,
    withdrawalChance: 0,
    collateralDamage: 0,
    collateralDamageLimit: 0,
    collateralDamageMaxUnits: 0,
    combatLimit: 100,
    unitCombatType: "melee",
    immuneToFirstStrikes: false,
    bonusVsMelee: 25,
  },
  {
    id: "swordsman",
    name: "Swordsman",
    image: "assets/units/Swordsman.png",
    strength: 6,
    cost: 40,
    moves: 1,
    firstStrikes: 0,
    firstStrikeChances: 0,
    withdrawalChance: 0,
    collateralDamage: 0,
    collateralDamageLimit: 0,
    collateralDamageMaxUnits: 0,
    combatLimit: 100,
    unitCombatType: "melee",
    immuneToFirstStrikes: false,
    cityAttackBonus: 10,
  },
  {
    id: "celtic_gallic_warrior",
    replaces: "swordsman",
    name: "Gallic Warrior",
    image: "assets/units/Gallic Warrior.png",
    strength: 6,
    cost: 40,
    moves: 1,
    firstStrikes: 0,
    firstStrikeChances: 0,
    withdrawalChance: 0,
    collateralDamage: 0,
    collateralDamageLimit: 0,
    collateralDamageMaxUnits: 0,
    combatLimit: 100,
    unitCombatType: "melee",
    immuneToFirstStrikes: false,
    cityAttackBonus: 10,
    freePromotions: ['guerilla1'],
  },
  {
    id: "longbowman",
    name: "Longbowman",
    image: "assets/units/Longbowman.png",
    strength: 6,
    cost: 50,
    moves: 1,
    firstStrikes: 1,
    firstStrikeChances: 0,
    withdrawalChance: 0,
    collateralDamage: 0,
    collateralDamageLimit: 0,
    collateralDamageMaxUnits: 0,
    combatLimit: 100,
    unitCombatType: "archery",
    immuneToFirstStrikes: false,
    cityDefenseBonus: 25,
    hillsDefenseBonus: 25,
  },
  {
    id: "horse_archer",
    name: "Horse Archer",
    image: "assets/units/Horse Archer.png",
    strength: 6,
    cost: 50,
    moves: 2,
    firstStrikes: 0,
    firstStrikeChances: 0,
    withdrawalChance: 20,
    collateralDamage: 0,
    collateralDamageLimit: 0,
    collateralDamageMaxUnits: 0,
    combatLimit: 100,
    unitCombatType: "mounted",
    immuneToFirstStrikes: true,
    noDefensiveBonus: true,
    attackBonusVsCatapults: 50,
    flankingStrikes: { catapult: 100, trebuchet: 100 },
  },
  {
    id: "mongol_keshik",
    replaces: "horse_archer",
    name: "Keshik",
    image: "assets/units/Keshik.png",
    strength: 6,
    cost: 50,
    moves: 2,
    firstStrikes: 1,
    firstStrikeChances: 0,
    withdrawalChance: 20,
    collateralDamage: 0,
    collateralDamageLimit: 0,
    collateralDamageMaxUnits: 0,
    combatLimit: 100,
    unitCombatType: "mounted",
    immuneToFirstStrikes: false,
    noDefensiveBonus: true,
    attackBonusVsCatapults: 50,
    flankingStrikes: { catapult: 100, trebuchet: 100 },
  },
  {
    id: "pikeman",
    name: "Pikeman",
    image: "assets/units/Pikeman.png",
    strength: 6,
    cost: 60,
    moves: 1,
    firstStrikes: 0,
    firstStrikeChances: 0,
    withdrawalChance: 0,
    collateralDamage: 0,
    collateralDamageLimit: 0,
    collateralDamageMaxUnits: 0,
    combatLimit: 100,
    unitCombatType: "melee",
    immuneToFirstStrikes: false,
    bonusVsMounted: 100,
  },
  {
    id: "crossbowman",
    name: "Crossbowman",
    image: "assets/units/Crossbowman.png",
    strength: 6,
    cost: 60,
    moves: 1,
    firstStrikes: 1,
    firstStrikeChances: 0,
    withdrawalChance: 0,
    collateralDamage: 0,
    collateralDamageLimit: 0,
    collateralDamageMaxUnits: 0,
    combatLimit: 100,
    unitCombatType: "archery",
    immuneToFirstStrikes: false,
    bonusVsMelee: 50,
  },
  {
    id: "china_chokonu",
    replaces: "crossbowman",
    name: "Cho-Ko-Nu",
    image: "assets/units/Cho-Ko-Nu.png",
    strength: 6,
    cost: 60,
    moves: 1,
    firstStrikes: 2,
    firstStrikeChances: 0,
    withdrawalChance: 0,
    collateralDamage: 50,
    collateralDamageLimit: 60,
    collateralDamageMaxUnits: 5,
    combatLimit: 100,
    unitCombatType: "archery",
    immuneToFirstStrikes: false,
    bonusVsMelee: 50,
    freePromotions: ['cityGarrison1', 'drill1'],
  },
  {
    id: "holy_roman_landsknecht",
    replaces: "pikeman",
    name: "Landsknecht",
    image: "assets/units/Landsknecht.png",
    strength: 6,
    cost: 60,
    moves: 1,
    firstStrikes: 0,
    firstStrikeChances: 0,
    withdrawalChance: 0,
    collateralDamage: 0,
    collateralDamageLimit: 0,
    collateralDamageMaxUnits: 0,
    combatLimit: 100,
    unitCombatType: "melee",
    immuneToFirstStrikes: false,
    bonusVsMounted: 100,
    bonusVsMelee: 100,
  },
  {
    id: "netherlands_oostindievaarder",
    replaces: "galleon",
    name: "East Indiaman",
    image: "assets/units/East Indiaman.png",
    strength: 6,
    cost: 80,
    moves: 4,
    firstStrikes: 0,
    firstStrikeChances: 0,
    withdrawalChance: 0,
    collateralDamage: 0,
    collateralDamageLimit: 0,
    collateralDamageMaxUnits: 0,
    combatLimit: 100,
    unitCombatType: "naval",
    immuneToFirstStrikes: false,
  },
  {
    id: "privateer",
    name: "Privateer",
    image: "assets/units/Privateer.png",
    strength: 6,
    cost: 80,
    moves: 4,
    firstStrikes: 0,
    firstStrikeChances: 0,
    withdrawalChance: 0,
    collateralDamage: 0,
    collateralDamageLimit: 0,
    collateralDamageMaxUnits: 0,
    combatLimit: 100,
    unitCombatType: "naval",
    immuneToFirstStrikes: false,
  },
  {
    id: "rome_praetorian",
    replaces: "swordsman",
    name: "Praetorian",
    image: "assets/units/Praetorian.png",
    strength: 8,
    cost: 45,
    moves: 1,
    firstStrikes: 0,
    firstStrikeChances: 0,
    withdrawalChance: 0,
    collateralDamage: 0,
    collateralDamageLimit: 0,
    collateralDamageMaxUnits: 0,
    combatLimit: 100,
    unitCombatType: "melee",
    immuneToFirstStrikes: false,
  },
  {
    id: "war_elephant",
    name: "War Elephant",
    image: "assets/units/War Elephant.png",
    strength: 8,
    cost: 60,
    moves: 1,
    firstStrikes: 0,
    firstStrikeChances: 0,
    withdrawalChance: 0,
    collateralDamage: 0,
    collateralDamageLimit: 0,
    collateralDamageMaxUnits: 0,
    combatLimit: 100,
    unitCombatType: "mounted",
    immuneToFirstStrikes: false,
    noDefensiveBonus: true,
    bonusVsMounted: 50,
  },
  {
    id: "khmer_ballista_elephant",
    replaces: "war_elephant",
    name: "Ballista Elephant",
    image: "assets/units/Ballista Elephant.png",
    strength: 8,
    cost: 60,
    moves: 1,
    firstStrikes: 0,
    firstStrikeChances: 0,
    withdrawalChance: 0,
    collateralDamage: 0,
    collateralDamageLimit: 0,
    collateralDamageMaxUnits: 0,
    combatLimit: 100,
    unitCombatType: "mounted",
    immuneToFirstStrikes: false,
    noDefensiveBonus: true,
    bonusVsMounted: 50,
    unitCombatTargets: ["mounted"],
  },
  {
    id: "maceman",
    name: "Maceman",
    image: "assets/units/Maceman.png",
    strength: 8,
    cost: 70,
    moves: 1,
    firstStrikes: 0,
    firstStrikeChances: 0,
    withdrawalChance: 0,
    collateralDamage: 0,
    collateralDamageLimit: 0,
    collateralDamageMaxUnits: 0,
    combatLimit: 100,
    unitCombatType: "melee",
    immuneToFirstStrikes: false,
    bonusVsMelee: 50,
  },
  {
    id: "japan_samurai",
    replaces: "maceman",
    name: "Samurai",
    image: "assets/units/Samurai.png",
    strength: 8,
    cost: 70,
    moves: 1,
    firstStrikes: 2,
    firstStrikeChances: 0,
    withdrawalChance: 0,
    collateralDamage: 0,
    collateralDamageLimit: 0,
    collateralDamageMaxUnits: 0,
    combatLimit: 100,
    unitCombatType: "melee",
    immuneToFirstStrikes: false,
    bonusVsMelee: 50,
    freePromotions: ['drill1', 'combat1'],
  },
  {
    id: "viking_beserker",
    replaces: "maceman",
    name: "Berserker",
    image: "assets/units/Berserker.png",
    strength: 8,
    cost: 70,
    moves: 1,
    firstStrikes: 0,
    firstStrikeChances: 0,
    withdrawalChance: 0,
    collateralDamage: 0,
    collateralDamageLimit: 0,
    collateralDamageMaxUnits: 0,
    combatLimit: 100,
    unitCombatType: "melee",
    immuneToFirstStrikes: false,
    cityAttackBonus: 10,
    bonusVsMelee: 50,
    freePromotions: ['amphibious', 'combat1'],
  },
  {
    id: "frigate",
    name: "Frigate",
    image: "assets/units/Frigate.png",
    strength: 8,
    cost: 90,
    moves: 4,
    firstStrikes: 0,
    firstStrikeChances: 0,
    withdrawalChance: 0,
    collateralDamage: 0,
    collateralDamageLimit: 0,
    collateralDamageMaxUnits: 0,
    combatLimit: 100,
    unitCombatType: "naval",
    immuneToFirstStrikes: false,
  },
  {
    id: "ship_of_the_line",
    name: "Ship of the Line",
    image: "assets/units/Ship of the Line.png",
    strength: 8,
    cost: 120,
    moves: 3,
    firstStrikes: 0,
    firstStrikeChances: 0,
    withdrawalChance: 0,
    collateralDamage: 0,
    collateralDamageLimit: 0,
    collateralDamageMaxUnits: 0,
    combatLimit: 100,
    unitCombatType: "naval",
    immuneToFirstStrikes: false,
    attackBonusVsFrigates: 50,
    defenseBonusVsFrigates: 50,
  },
  {
    id: "musketman",
    name: "Musketman",
    image: "assets/units/Musketman.png",
    strength: 9,
    cost: 80,
    moves: 1,
    firstStrikes: 0,
    firstStrikeChances: 0,
    withdrawalChance: 0,
    collateralDamage: 0,
    collateralDamageLimit: 0,
    collateralDamageMaxUnits: 0,
    combatLimit: 100,
    unitCombatType: "gun",
    immuneToFirstStrikes: false,
    ignoreBuildingDefense: true,
  },
  {
    id: "french_musketeer",
    replaces: "musketman",
    name: "Musketeer",
    image: "assets/units/Musketeer.png",
    strength: 9,
    cost: 80,
    moves: 2,
    firstStrikes: 0,
    firstStrikeChances: 0,
    withdrawalChance: 0,
    collateralDamage: 0,
    collateralDamageLimit: 0,
    collateralDamageMaxUnits: 0,
    combatLimit: 100,
    unitCombatType: "gun",
    immuneToFirstStrikes: false,
    ignoreBuildingDefense: true,
  },
  {
    id: "ottoman_janissary",
    replaces: "musketman",
    name: "Janissary",
    image: "assets/units/Janissary.png",
    strength: 9,
    cost: 80,
    moves: 1,
    firstStrikes: 0,
    firstStrikeChances: 0,
    withdrawalChance: 0,
    collateralDamage: 0,
    collateralDamageLimit: 0,
    collateralDamageMaxUnits: 0,
    combatLimit: 100,
    unitCombatType: "gun",
    immuneToFirstStrikes: false,
    bonusVsMelee: 25,
    bonusVsArcher: 25,
    bonusVsMounted: 25,
    ignoreBuildingDefense: true,
  },
  {
    id: "ethiopian_oromo_warrior",
    replaces: "musketman",
    name: "Oromo Warrior",
    image: "assets/units/Oromo Warrior.png",
    strength: 9,
    cost: 80,
    moves: 1,
    firstStrikes: 1,
    firstStrikeChances: 0,
    withdrawalChance: 0,
    collateralDamage: 0,
    collateralDamageLimit: 0,
    collateralDamageMaxUnits: 0,
    combatLimit: 100,
    unitCombatType: "gun",
    immuneToFirstStrikes: true,
    freePromotions: ['drill1', 'drill2'],
    ignoreBuildingDefense: true,
  },
  {
    id: "knight",
    name: "Knight",
    image: "assets/units/Knight.png",
    strength: 10,
    cost: 90,
    moves: 2,
    firstStrikes: 0,
    firstStrikeChances: 0,
    withdrawalChance: 0,
    collateralDamage: 0,
    collateralDamageLimit: 0,
    collateralDamageMaxUnits: 0,
    combatLimit: 100,
    unitCombatType: "mounted",
    immuneToFirstStrikes: true,
    noDefensiveBonus: true,
    flankingStrikes: { catapult: 100, trebuchet: 100 },
  },
  {
    id: "arabia_camelarcher",
    replaces: "knight",
    name: "Camel Archer",
    image: "assets/units/Camel Archer.png",
    strength: 10,
    cost: 90,
    moves: 2,
    firstStrikes: 0,
    firstStrikeChances: 0,
    withdrawalChance: 15,
    collateralDamage: 0,
    collateralDamageLimit: 0,
    collateralDamageMaxUnits: 0,
    combatLimit: 100,
    unitCombatType: "mounted",
    immuneToFirstStrikes: true,
    noDefensiveBonus: true,
    flankingStrikes: { catapult: 100, trebuchet: 100 },
  },
  {
    id: "spanish_conquistador",
    replaces: "cuirassier",
    name: "Conquistador",
    image: "assets/units/Conquistador.png",
    strength: 12,
    cost: 100,
    moves: 2,
    firstStrikes: 0,
    firstStrikeChances: 0,
    withdrawalChance: 15,
    collateralDamage: 0,
    collateralDamageLimit: 0,
    collateralDamageMaxUnits: 0,
    combatLimit: 100,
    unitCombatType: "mounted",
    immuneToFirstStrikes: true,
    bonusVsMelee: 50,
    ignoreBuildingDefense: true,
    flankingStrikes: { catapult: 100, trebuchet: 100 },
  },
  {
    id: "byzantine_cataphract",
    replaces: "knight",
    name: "Cataphract",
    image: "assets/units/Cataphract.png",
    strength: 12,
    cost: 90,
    moves: 2,
    firstStrikes: 0,
    firstStrikeChances: 0,
    withdrawalChance: 0,
    collateralDamage: 0,
    collateralDamageLimit: 0,
    collateralDamageMaxUnits: 0,
    combatLimit: 100,
    unitCombatType: "mounted",
    immuneToFirstStrikes: false,
    noDefensiveBonus: true,
    flankingStrikes: { catapult: 100, trebuchet: 100 },
  },
  {
    id: "grenadier",
    name: "Grenadier",
    image: "assets/units/Grenadier.png",
    strength: 12,
    cost: 100,
    moves: 1,
    firstStrikes: 0,
    firstStrikeChances: 0,
    withdrawalChance: 0,
    collateralDamage: 0,
    collateralDamageLimit: 0,
    collateralDamageMaxUnits: 0,
    combatLimit: 100,
    unitCombatType: "gun",
    immuneToFirstStrikes: false,
    attackBonusVsRiflemen: 50,
    ignoreBuildingDefense: true,
  },
  {
    id: "cannon",
    name: "Cannon",
    image: "assets/units/Cannon.png",
    strength: 12,
    cost: 100,
    moves: 1,
    firstStrikes: 0,
    firstStrikeChances: 0,
    withdrawalChance: 0,
    collateralDamage: 100,
    collateralDamageLimit: 60,
    collateralDamageMaxUnits: 7,
    combatLimit: 80,
    unitCombatType: "siege",
    immuneToFirstStrikes: false,
    noDefensiveBonus: true,
    ignoreBuildingDefense: true,
    collateralImmuneVs: ["siege"],
  },
  {
    id: "ironclad",
    name: "Ironclad",
    image: "assets/units/Ironclad.png",
    strength: 12,
    cost: 100,
    moves: 2,
    firstStrikes: 0,
    firstStrikeChances: 0,
    withdrawalChance: 0,
    collateralDamage: 0,
    collateralDamageLimit: 0,
    collateralDamageMaxUnits: 0,
    combatLimit: 100,
    unitCombatType: "naval",
    immuneToFirstStrikes: false,
  },
  {
    id: "cuirassier",
    name: "Cuirassier",
    image: "assets/units/Cuirassier.png",
    strength: 12,
    cost: 100,
    moves: 2,
    firstStrikes: 0,
    firstStrikeChances: 0,
    withdrawalChance: 15,
    collateralDamage: 0,
    collateralDamageLimit: 0,
    collateralDamageMaxUnits: 0,
    combatLimit: 100,
    unitCombatType: "mounted",
    immuneToFirstStrikes: true,
    noDefensiveBonus: true,
    ignoreBuildingDefense: true,
    flankingStrikes: { catapult: 100, trebuchet: 100, cannon: 100 },
  },
  {
    id: "rifleman",
    name: "Rifleman",
    image: "assets/units/Rifleman.png",
    strength: 14,
    cost: 110,
    moves: 1,
    firstStrikes: 0,
    firstStrikeChances: 0,
    withdrawalChance: 0,
    collateralDamage: 0,
    collateralDamageLimit: 0,
    collateralDamageMaxUnits: 0,
    combatLimit: 100,
    unitCombatType: "gun",
    immuneToFirstStrikes: false,
    bonusVsMounted: 25,
    ignoreBuildingDefense: true,
  },
  {
    id: "english_redcoat",
    replaces: "rifleman",
    name: "Redcoat",
    image: "assets/units/Redcoat.png",
    strength: 14,
    cost: 110,
    moves: 1,
    firstStrikes: 0,
    firstStrikeChances: 0,
    withdrawalChance: 0,
    collateralDamage: 0,
    collateralDamageLimit: 0,
    collateralDamageMaxUnits: 0,
    combatLimit: 100,
    unitCombatType: "gun",
    immuneToFirstStrikes: false,
    bonusVsMounted: 25,
    bonusVsGun: 25,
    ignoreBuildingDefense: true,
  },
  {
    id: "cavalry",
    name: "Cavalry",
    image: "assets/units/Cavalry.png",
    strength: 15,
    cost: 120,
    moves: 2,
    firstStrikes: 0,
    firstStrikeChances: 0,
    withdrawalChance: 30,
    collateralDamage: 0,
    collateralDamageLimit: 0,
    collateralDamageMaxUnits: 0,
    combatLimit: 100,
    unitCombatType: "mounted",
    immuneToFirstStrikes: false,
    noDefensiveBonus: true,
    ignoreBuildingDefense: true,
    attackBonusVsCannons: 50,
    flankingStrikes: { catapult: 100, trebuchet: 100, cannon: 100 },
  },
  {
    id: "russia_cossack",
    replaces: "cavalry",
    name: "Cossack",
    image: "assets/units/Cossack.png",
    strength: 15,
    cost: 120,
    moves: 2,
    firstStrikes: 0,
    firstStrikeChances: 0,
    withdrawalChance: 30,
    collateralDamage: 0,
    collateralDamageLimit: 0,
    collateralDamageMaxUnits: 0,
    combatLimit: 100,
    unitCombatType: "mounted",
    immuneToFirstStrikes: false,
    noDefensiveBonus: true,
    ignoreBuildingDefense: true,
    bonusVsMounted: 50,
    attackBonusVsCannons: 50,
    flankingStrikes: { catapult: 100, trebuchet: 100, cannon: 100 },
  },
];

// Unit combat types used in data: recon, melee, archery, mounted, siege, gun, naval
const ALL_LAND = ['recon', 'archery', 'mounted', 'melee', 'gun', 'siege'];
const ALL_LAND_NAVAL = [...ALL_LAND, 'naval'];

export const PROMOTIONS = [
  // ── Combat line ──
  { id: 'combat1',  name: 'Combat I',   image: 'assets/promotions/combat1.gif',  effect: '+10% Strength', strengthPercent: 10, requires: [], unitCombatTypes: ['recon','archery','mounted','melee','gun','naval'] },
  { id: 'combat2',  name: 'Combat II',  image: 'assets/promotions/combat2.gif',  effect: '+10% Strength', strengthPercent: 10, requires: ['combat1'], unitCombatTypes: ['recon','archery','mounted','melee','gun','naval'] },
  { id: 'combat3',  name: 'Combat III', image: 'assets/promotions/combat3.gif',  effect: '+10% Strength', strengthPercent: 10, requires: ['combat2'], unitCombatTypes: ['recon','archery','mounted','melee','gun','naval'] },
  { id: 'combat4',  name: 'Combat IV',  image: 'assets/promotions/combat4.gif',  effect: '+10% Strength; Heals Extra 10% Damage/Turn in Neutral Lands', strengthPercent: 10, requires: ['combat3'], unitCombatTypes: ['recon','archery','mounted','melee','gun','naval'] },
  { id: 'combat5',  name: 'Combat V',   image: 'assets/promotions/combat5.gif',  effect: '+10% Strength; Heals Extra 10% Damage/Turn in Enemy Lands',    strengthPercent: 10, requires: ['combat4'], unitCombatTypes: ['recon','archery','mounted','melee','gun','naval'] },
  { id: 'combat6',  name: 'Combat VI',  image: 'assets/promotions/combat6.gif',  effect: '+25% Strength', strengthPercent: 25, requires: ['leader'], requiresAny: ['combat5'], unitCombatTypes: ['recon','archery','mounted','melee','gun','naval'] },

  // ── City Raider line ──
  { id: 'cityRaider1', name: 'City Raider I',   image: 'assets/promotions/city_raider1.gif', effect: '+20% City Attack', cityAttackPercent: 20, requires: [], unitCombatTypes: ['melee','siege'] },
  { id: 'cityRaider2', name: 'City Raider II',  image: 'assets/promotions/city_raider2.gif', effect: '+25% City Attack', cityAttackPercent: 25, requires: ['cityRaider1'], unitCombatTypes: ['melee','siege'] },
  { id: 'cityRaider3', name: 'City Raider III', image: 'assets/promotions/city_raider3.gif', effect: '+30% City Attack; +10% vs Gunpowder Units', cityAttackPercent: 30, strengthPercentVsGun: 10, requires: ['cityRaider2'], unitCombatTypes: ['melee','siege'] },

  // ── City Garrison line ──
  { id: 'cityGarrison1', name: 'City Garrison I',   image: 'assets/promotions/city_garrison1.gif', effect: '+20% City Defense', cityDefensePercent: 20, requires: [], unitCombatTypes: ['archery','gun'] },
  { id: 'cityGarrison2', name: 'City Garrison II',  image: 'assets/promotions/city_garrison2.gif', effect: '+25% City Defense', cityDefensePercent: 25, requires: ['cityGarrison1'], unitCombatTypes: ['archery','gun'] },
  { id: 'cityGarrison3', name: 'City Garrison III', image: 'assets/promotions/city_garrison3.gif', effect: '+30% City Defense; +10% vs Melee Units', cityDefensePercent: 30, strengthPercentVsMelee: 10, requires: ['cityGarrison2'], unitCombatTypes: ['archery','gun'] },

  // ── Drill line ──
  { id: 'drill1', name: 'Drill I',  image: 'assets/promotions/drill1.gif', effect: '+1 First Strike Chance',  firstStrikeChances: 1, requires: [], unitCombatTypes: ['archery','siege','gun','naval'] },
  { id: 'drill2', name: 'Drill II', image: 'assets/promotions/drill2.gif', effect: '+1 First Strike; Suffers 20% Less Collateral Damage', firstStrikes: 1, collateralDamageProtection: 20, requires: ['drill1'], unitCombatTypes: ['archery','siege','gun','melee','naval'] },
  { id: 'drill3', name: 'Drill III', image: 'assets/promotions/drill3.gif', effect: '+2 First Strike Chances; Suffers 20% Less Collateral Damage', firstStrikeChances: 2, collateralDamageProtection: 20, requires: ['drill2'], unitCombatTypes: ['archery','siege','gun','melee','naval'] },
  { id: 'drill4', name: 'Drill IV',  image: 'assets/promotions/drill4.gif', effect: '+2 First Strikes; Suffers 20% Less Collateral Damage; +10% vs Mounted Units', firstStrikes: 2, collateralDamageProtection: 20, strengthPercentVsMounted: 10, requires: ['drill3'], unitCombatTypes: ['archery','siege','gun','melee','naval'] },

  // ── Barrage line ──
  { id: 'barrage1', name: 'Barrage I',   image: 'assets/promotions/barrage1.gif', effect: '+20 Collateral Damage',  collateralDamageChange: 20, requires: [], unitCombatTypes: ['siege','naval'] },
  { id: 'barrage2', name: 'Barrage II',  image: 'assets/promotions/barrage2.gif', effect: '+30 Collateral Damage; +10% vs Melee Units', collateralDamageChange: 30, strengthPercentVsMelee: 10, requires: ['barrage1'], unitCombatTypes: ['siege','naval'] },
  { id: 'barrage3', name: 'Barrage III', image: 'assets/promotions/barrage3.gif', effect: '+50 Collateral Damage; +10% vs Gunpowder Units', collateralDamageChange: 50, strengthPercentVsGun: 10, requires: ['barrage2'], unitCombatTypes: ['siege','naval'] },

  // ── Flanking line ──
  { id: 'flanking1', name: 'Flanking I',  image: 'assets/promotions/flanking1.gif', effect: '+10% Withdrawal Chance', withdrawalChance: 10, requires: [], unitCombatTypes: ['mounted','naval'] },
  { id: 'flanking2', name: 'Flanking II', image: 'assets/promotions/flanking2.gif', effect: '+20% Withdrawal Chance; Immune to First Strikes', withdrawalChance: 20, immuneToFirstStrikes: true, requires: ['flanking1'], unitCombatTypes: ['mounted','naval'] },

  // ── Woodsman line ──
  { id: 'woodsman1', name: 'Woodsman I',   image: 'assets/promotions/woodsman1.gif', effect: '+20% Jungle Defense; +20% Forest Defense', featureDefensePercent: 20, requires: [], unitCombatTypes: ['recon','melee','gun'] },
  { id: 'woodsman2', name: 'Woodsman II',  image: 'assets/promotions/woodsman2.gif', effect: '+30% Jungle Defense; +30% Forest Defense; Double Movement in Jungle and Forests', featureDefensePercent: 30, requires: ['woodsman1'], unitCombatTypes: ['recon','melee','gun'] },
  { id: 'woodsman3', name: 'Woodsman III', image: 'assets/promotions/woodsman3.gif', effect: '+2 First Strikes; +50% Forest/Jungle Attack; Heals Units in Same Tile Extra 15%', firstStrikes: 2, featureAttackPercent: 50, requires: ['woodsman2'], unitCombatTypes: ['melee','gun'] },

  // ── Guerilla line ──
  { id: 'guerilla1', name: 'Guerilla I',   image: 'assets/promotions/guerilla1.gif', effect: '+20% Hills Defense', hillsDefensePercent: 20, requires: [], unitCombatTypes: ['recon','archery','gun'] },
  { id: 'guerilla2', name: 'Guerilla II',  image: 'assets/promotions/guerilla2.gif', effect: '+30% Hills Defense; Double Movement in Hills', hillsDefensePercent: 30, requires: ['guerilla1'], unitCombatTypes: ['recon','archery','gun','melee'] },
  { id: 'guerilla3', name: 'Guerilla III', image: 'assets/promotions/guerilla3.gif', effect: '+25% Hills Attack; +50% Withdrawal Chance', hillsAttackPercent: 25, withdrawalChance: 50, requires: ['guerilla2'], unitCombatTypes: ['archery','gun','melee'] },

  // ── vs unit type ──
  { id: 'shock',     name: 'Shock',      image: 'assets/promotions/shock.gif',     effect: '+25% vs Melee Units',    strengthPercentVsMelee: 25,   requires: [], requiresAny: ['combat1','drill1'], unitCombatTypes: ['archery','mounted','melee','siege'] },
  { id: 'cover',     name: 'Cover',      image: 'assets/promotions/cover.gif',     effect: '+25% vs Archery Units',  strengthPercentVsArchery: 25, requires: [], requiresAny: ['combat1','drill1'], unitCombatTypes: ['archery','melee','gun'] },
  { id: 'charge',    name: 'Charge',     image: 'assets/promotions/charge.gif',    effect: '+25% vs Siege Weapons',  strengthPercentVsSiege: 25, requires: [], requiresAny: ['combat1'], unitCombatTypes: ['mounted','melee'] },
  { id: 'ambush',    name: 'Ambush',     image: 'assets/promotions/ambush.gif',    effect: '+25% vs Armored Units',  strengthPercentVsArmor: 25, requires: [], requiresAny: ['combat2','drill2'], unitCombatTypes: ['siege','gun'] },
  { id: 'pinch',     name: 'Pinch',      image: 'assets/promotions/pinch.gif',     effect: '+25% vs Gunpowder Units', strengthPercentVsGun: 25, requires: [], requiresAny: ['combat1','drill1'], unitCombatTypes: ['mounted','gun'] },
  { id: 'formation', name: 'Formation',  image: 'assets/promotions/formation.gif', effect: '+25% vs Mounted Units',  strengthPercentVsMounted: 25, requires: [], requiresAny: ['combat2','drill2'], unitCombatTypes: ['archery','mounted','melee','gun'] },
  { id: 'amphibious', name: 'Amphibious', image: 'assets/promotions/amphibious.gif', effect: 'No Combat Penalty for Attacking from Sea; No Combat Penalty Attacking Across River', requires: [], requiresAny: ['combat2'], unitCombatTypes: ['recon','archery','mounted','melee','gun'] },

  // ── Advanced ──
  { id: 'blitz', name: 'Blitz', image: 'assets/promotions/blitz.gif', effect: 'Can Attack Multiple Times Per Turn', requires: ['combat3'], unitCombatTypes: ['mounted','naval'] },

  // ── Great General promotions ──
  { id: 'tactics', name: 'Tactics', image: 'assets/promotions/tactics.gif', effect: '+30% Withdrawal Chance', withdrawalChance: 30, requires: [], unitCombatTypes: ALL_LAND_NAVAL },
];

export const TERRAIN_BONUSES = {
  flat:        { defenseBonus: 0,  label: 'Flat',          short: 'Flat +0%',         icon: 'ph-sun-horizon' },
  hill:        { defenseBonus: 25, label: 'Hill',          short: 'Hill +25%',        icon: 'ph-mountains' },
  forest:      { defenseBonus: 50, label: 'Forest / Jungle',      short: 'Forest/Jungle +50%',      icon: 'ph-tree' },
  hillForest:  { defenseBonus: 75, label: 'Forested / Jungle Hill', short: 'Hill forest/jungle +75%', icon: 'ph-tree', icon2: 'ph-mountains' },
};

// SDK: fortifyModifier() = getFortifyTurns() * GC.getFORTIFY_MODIFIER_PER_TURN()
// BTS: FORTIFY_MODIFIER_PER_TURN = 5, MAX_FORTIFY_TURNS = 5 (so max = 25%)
export const FORTIFICATION_BONUSES = {
  none:   { defenseBonus: 0,  label: 'None',                     short: 'None' },
  fort5:  { defenseBonus: 5,  label: 'Fortified (1 turn, +5%)',  short: '1 turn +5%' },
  fort10: { defenseBonus: 10, label: 'Fortified (2 turns, +10%)', short: '2 turns +10%' },
  fort15: { defenseBonus: 15, label: 'Fortified (3 turns, +15%)', short: '3 turns +15%' },
  fort20: { defenseBonus: 20, label: 'Fortified (4 turns, +20%)', short: '4 turns +20%' },
  fort25: { defenseBonus: 25, label: 'Fortified (5 turns, +25%)', short: '5 turns +25%' },
};

export const SEA_TERRAIN_BONUSES = {
  ocean:   { defenseBonus: 0,  label: 'Ocean',          short: 'Ocean +0%' },
  coastal: { defenseBonus: 10, label: 'Coastal / Lake', short: 'Coastal +10%' },
};

export const CITY_BUILDING_BONUSES = {
  none:   { defenseBonus: 0,   short: 'No walls +0%',  icon: 'ph-house-simple' },
  walls:  { defenseBonus: 50,  short: 'Walls +50%',    icon: 'ph-wall' },
  castle: { defenseBonus: 100, short: 'Castle +100%',  icon: 'ph-castle-turret' },
};

export const CITY_CULTURE_BONUSES = {
  none:        { defenseBonus: 0,   short: 'New city +0%' },
  fledgling:   { defenseBonus: 20,  short: 'Fledgling +20%' },
  developing:  { defenseBonus: 40,  short: 'Developing +40%' },
  refined:     { defenseBonus: 60,  short: 'Refined +60%' },
  influential: { defenseBonus: 80,  short: 'Influential +80%' },
  legendary:   { defenseBonus: 100, short: 'Legendary +100%' },
};

export const COMBAT_GLOBALS = {
  maxHP: 100,
  baseDamagePerRound: 20, // GC: COMBAT_DAMAGE
  combatRounds: function (hp) {
    // number of hits needed to reduce hp to 0
    return Math.ceil(hp / this.baseDamagePerRound);
  },
};
